-- ClienteZero MVP schema for Supabase (PostgreSQL)
-- Run this in Supabase SQL Editor before starting the app.

create table if not exists public.app_user (
  id bigint primary key generated by default as identity,
  nome text not null,
  tel text not null,
  email text
);

create table if not exists public.fatura (
  id bigint primary key generated by default as identity,
  id_user bigint not null references public.app_user(id) on delete cascade,
  situ integer not null default 0 check (situ in (0, 1)),
  valor numeric(10, 2),
  forma text,
  vencimento timestamptz
);

create index if not exists idx_fatura_user_situ on public.fatura(id_user, situ);

create table if not exists public.acesso (
  id bigint primary key generated by default as identity,
  id_user bigint not null references public.app_user(id) on delete cascade,
  dados text not null
);

create index if not exists idx_acesso_user on public.acesso(id_user);

create table if not exists public.automation_log (
  id bigint primary key generated by default as identity,
  id_user bigint not null references public.app_user(id),
  id_fatura bigint references public.fatura(id),
  mp_payment_id varchar(100),
  status text not null check (status in ('success', 'error')),
  erro text,
  whatsapp_enviado boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_automation_log_user_date on public.automation_log(id_user, created_at desc);
