-- ClienteZero — Schema expansion v2
-- Run after 001_init_schema.sql

-- -------------------------------------------------------
-- Planos de assinatura
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS plano (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        TEXT NOT NULL,
  valor       NUMERIC(10,2) NOT NULL,
  dias_vigencia INT NOT NULL DEFAULT 30,
  ativo       BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------
-- Expandir app_user
-- -------------------------------------------------------
ALTER TABLE app_user
  ADD COLUMN IF NOT EXISTS plano_id       BIGINT REFERENCES plano(id),
  ADD COLUMN IF NOT EXISTS ativo          BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS data_vencimento DATE;

-- -------------------------------------------------------
-- Expandir fatura: situ=2 (cancelada), data_pagamento, mp_payment_id
-- -------------------------------------------------------
ALTER TABLE fatura
  ADD COLUMN IF NOT EXISTS data_pagamento TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS mp_payment_id  VARCHAR(100);

ALTER TABLE fatura DROP CONSTRAINT IF EXISTS fatura_situ_check;
ALTER TABLE fatura ADD CONSTRAINT fatura_situ_check CHECK (situ IN (0, 1, 2));

-- -------------------------------------------------------
-- Expandir acesso: ativo (false = acesso suspenso)
-- -------------------------------------------------------
ALTER TABLE acesso
  ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT true;

-- -------------------------------------------------------
-- Fila de jobs para retry (WhatsApp, etc.)
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_queue (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo           TEXT NOT NULL,
  payload        JSONB NOT NULL,
  tentativas     INT NOT NULL DEFAULT 0,
  max_tentativas INT NOT NULL DEFAULT 3,
  status         TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  proximo_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
  erro           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_queue_pending
  ON job_queue(status, proximo_em)
  WHERE status = 'pending';
