-- ClienteZero — Schema expansion v3
-- Run after 002_expand_schema.sql

-- -------------------------------------------------------
-- Servidores IPTV
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS servidor (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            TEXT NOT NULL,
  url_base        TEXT NOT NULL,
  usuario_painel  TEXT,
  senha_painel    TEXT,
  porta           INT,
  protocolo       TEXT NOT NULL DEFAULT 'http',
  max_conexoes    INT,
  ativo           BOOLEAN NOT NULL DEFAULT true,
  notas           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------
-- Vincular plano ao servidor (cada servidor tem seus planos e preços)
-- -------------------------------------------------------
ALTER TABLE plano
  ADD COLUMN IF NOT EXISTS servidor_id BIGINT REFERENCES servidor(id);

-- -------------------------------------------------------
-- Produtos / Add-ons (telas extras, VOD, esportes, adulto, etc.)
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS produto (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            TEXT NOT NULL,
  descricao       TEXT,
  valor_adicional NUMERIC(10,2) NOT NULL DEFAULT 0,
  ativo           BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------
-- Associação cliente ↔ produtos (N:N)
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS cliente_produto (
  id_user    BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  id_produto BIGINT NOT NULL REFERENCES produto(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id_user, id_produto)
);

CREATE INDEX IF NOT EXISTS idx_cliente_produto_user ON cliente_produto(id_user);
