-- One-shot initialization: schema + seed for Supabase/Postgres
-- Run this file in Supabase SQL Editor or via psql to create tables and seed minimal data.

-- Schema (from sql/supabase/001_init_schema.sql)
create table if not exists public.app_user (
  id bigint primary key generated by default as identity,
  nome text not null,
  tel text not null,
  email text
);

create table if not exists public.fatura (
  id bigint primary key generated by default as identity,
  id_user bigint not null references public.app_user(id) on delete cascade,
  situ integer not null default 0 check (situ in (0, 1)),
  valor numeric(10, 2),
  forma text,
  vencimento timestamptz
);

create index if not exists idx_fatura_user_situ on public.fatura(id_user, situ);

create table if not exists public.acesso (
  id bigint primary key generated by default as identity,
  id_user bigint not null references public.app_user(id) on delete cascade,
  dados text not null
);

create index if not exists idx_acesso_user on public.acesso(id_user);

create table if not exists public.automation_log (
  id bigint primary key generated by default as identity,
  id_user bigint not null references public.app_user(id),
  id_fatura bigint references public.fatura(id),
  mp_payment_id varchar(100),
  status text not null check (status in ('success', 'error')),
  erro text,
  whatsapp_enviado boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_automation_log_user_date on public.automation_log(id_user, created_at desc);

-- Seed (from sql/seed.sql)
INSERT INTO public.app_user (nome, tel, email) VALUES ('Cliente Teste','+5511999999999','teste@example.com');
INSERT INTO public.fatura (id_user, situ, valor, forma, vencimento) VALUES (1,0,49.90,'mensalidade','2026-03-10');
INSERT INTO public.acesso (id_user, dados) VALUES (1, '<b>usuario:</b> user123 <br/> <b>senha:</b> pass123');
